# Railway frontend configuration with Caddy
[variables]
NPM_CONFIG_UPDATE_NOTIFIER = 'false'
NPM_CONFIG_FUND = 'false'

[phases.setup]
nixPkgs = ['nodejs-18_x']

# Download caddy from nix
[phases.caddy]
dependsOn = ['setup']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

# Format the Caddyfile
[phases.fmt]
dependsOn = ['caddy']
cmds = ['caddy fmt --overwrite Caddyfile']

[phases.install]
dependsOn = ['fmt']
cmds = ['npm ci']

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']

# Start caddy web server
[start]
cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1'